version: "3.3"

services:

    traefik:
        image: "traefik:v2.3"
        container_name: "traefik"
        command:
            - "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.web.http.redirections.entrypoint.to=web-secure"
            - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
            - "--entrypoints.web-secure.address=:443"
            - "--entrypoints.mysql.address=:3306"
            - "--providers.file.filename=/etc/traefik/dynamic/traefik.toml"
        ports:
            - "443:443" #Docker sends requests on port 443 to Traefik on port 443
            - "80:80"
            - "3306:3306"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - ./traefik/conf/traefik.toml:/etc/traefik/dynamic/traefik.toml
            - ./traefik/certs:/opt/traefik/certs
        networks: 
            - local_traefik
    whoami:
        image: "containous/whoami"
        container_name: "hello-world"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.whoami.rule=Host(`127.0.0.1`)"
            - "traefik.http.routers.whoami.entrypoints=web-secure"
            - "traefik.http.routers.whoami.tls=true"
            - "traefik.http.routers.whoami.tls.options=default"
        networks: 
            - local_traefik
networks:
    local_traefik: null