[tls]
  [tls.options]
    [tls.options.default]
      minVersion = "VersionTLS12"
      sniStrict = false
      cipherSuites = [
        "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
      ]
    [tls.options.snistrict]
      minVersion = "VersionTLS12"
      sniStrict = true
      cipherSuites = [
        "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
      ]
    [tls.options.mintls13]
      minVersion = "VersionTLS13"
      sniStrict = true
      #cipherSuites = [
        # TLS 1.3 cipher suites.
      #  "TLS_AES_128_GCM_SHA256",
      #  "TLS_AES_256_GCM_SHA384",
      #  "TLS_CHACHA20_POLY1305_SHA256"
      #]


  [[tls.certificates]]
    certFile = "/opt/traefik/certs/127.0.0.1.crt"
    keyFile = "/opt/traefik/certs/127.0.0.1.key"

  # [[tls.certificates]]
  #   certFile = "/opt/traefik/certs/wp.localhost.crt"
  #   keyFile = "/opt/traefik/certs/wp.localhost.key"

[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/opt/traefik/certs/127.0.0.1.crt"
      keyFile = "/opt/traefik/certs/127.0.0.1.key"